line_length:
  warning: 145
  error: 150
  ignores_function_declarations: false
  ignores_comments: true
  ignores_urls: true

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
